# Welcome to numpy tutorial 


In [1]:
import numpy as np
import pandas as pd

In [2]:
print("Hello World")

Hello World


In [3]:
myarr=np.array([[10,20,30,40]],np.int64)

In [4]:
myarr

array([[10, 20, 30, 40]])

In [5]:
myarr[0,1]

np.int64(20)

In [6]:
myarr.shape

(1, 4)

In [7]:
myarr.dtype

dtype('int64')

In [9]:
myarr

array([[10, 20, 30, 40]])

In [11]:
myarr[0,1]=45

In [12]:
myarr

array([[10, 45, 30, 40]])

# Array Creation:Conversion from other Python structures

In [14]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [15]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [16]:
listarray.dtype

dtype('int64')

In [17]:
listarray.shape

(3, 3)

In [18]:
listarray.size

9

# Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

In [19]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [20]:
zeros=np.zeros((2,5))

In [21]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
zeros.dtype

dtype('float64')

In [23]:
zeros.shape

(2, 5)

In [24]:
rng=np.arange(5)

In [25]:
rng

array([0, 1, 2, 3, 4])

In [28]:
lspace=np.linspace(1,50,10)

In [29]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [30]:
emp=np.empty((4,6))

In [31]:
emp

array([[6.95256841e-310, 6.95256839e-310, 0.00000000e+000,
        4.26521154e-312, 1.32883174e-311, 4.94065646e-324],
       [0.00000000e+000, 0.00000000e+000, 4.04738577e-320,
        0.00000000e+000, 1.23022346e-321, 1.32896644e-311],
       [1.06811422e-306, 9.45699680e-308, 0.00000000e+000,
        1.32896645e-311, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 5.53353523e-322, 1.11259940e-306,
        1.42420345e-306, 1.42410974e-306,             nan]])

In [32]:
emp_like=np.empty_like(lspace)

In [33]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [34]:
ide=np.identity(45)

In [35]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [37]:
ide.shape

(45, 45)

In [38]:
arr=np.arange(99)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
arr=arr.reshape(3,33)

In [41]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [42]:
arr=arr.ravel()

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [45]:
arr.shape

(99,)

In [63]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [64]:
arr1=np.array(x)

In [65]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
arr1.sum(axis=0)

array([12, 15, 18])

In [67]:
arr1.sum(axis=1)

array([ 6, 15, 24])

In [68]:
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [69]:
arr1.flat

In [70]:
for item in arr1.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [72]:
arr1.ndim

2

In [73]:
arr1.size

9

In [74]:
arr1.nbytes

72

In [75]:
one=np.array([1,3,4,634,2])

In [76]:
one.argmax()

np.int64(3)

In [77]:
one.argmin()

np.int64(0)

In [78]:
one.argsort()

array([0, 4, 1, 2, 3])

In [79]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
arr1.argmin()

np.int64(0)

In [81]:
arr1.argmax()

np.int64(8)

In [84]:
arr1.argmax(axis=0)

array([2, 2, 2])

In [85]:
arr1.argmax(axis=1)

array([2, 2, 2])

In [86]:
arr.argsort(axis=0)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [87]:
arr1.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
arr1.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [90]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
arr2=np.array([[1,2,1],[4,0,6],[8,1,0]])

In [92]:
arr1+arr2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  9,  9]])

In [93]:
arr1*arr2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  8,  0]])

In [95]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [96]:
arr1.sum()

np.int64(45)

In [97]:
arr1.max()

np.int64(9)

In [98]:
arr1.min()

np.int64(1)

In [99]:
np.where(arr1>5)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [100]:
type(np.where(arr1>5))

tuple

In [102]:
np.count_nonzero(arr1)

9

In [103]:
np.nonzero(arr1)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [104]:
arr1[1,2]=0

In [106]:
np.nonzero(arr1)

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 0, 1, 2]))

In [107]:
import sys

In [108]:
py_ar=[0,4,55,2]

In [109]:
np_ar=np.array(py_ar)

In [114]:
sys.getsizeof(1)*len(py_ar)

112

In [115]:
np_ar.itemsize * np_ar.size

32

In [116]:
np_ar.tolist()

[0, 4, 55, 2]

In [123]:
import pandas as pd

In [126]:
dict1={
    "name":['Ishvi','Aman','Tushar','Yamini'],
    "marks":[90,92,91,89],
    "city":['Delhi','Harayana','Rohini','Najafgarh']
}



In [127]:
df = pd.DataFrame(dict1)

In [128]:
df

name  marks       city
0   Ishvi     90      Delhi
1    Aman     92   Harayana
2  Tushar     91     Rohini
3  Yamini     89  Najafgarh

In [129]:
df.to_csv('friends.csv')

In [ ]:
df.to_csv('friends.csv')

In [130]:
df.head(2)

name  marks      city
0  Ishvi     90     Delhi
1   Aman     92  Harayana

In [131]:
df.tail(2)

name  marks       city
2  Tushar     91     Rohini
3  Yamini     89  Najafgarh

In [132]:
df.describe()

marks
count   4.000000
mean   90.500000
std     1.290994
min    89.000000
25%    89.750000
50%    90.500000
75%    91.250000
max    92.000000